### ISSUE TITLE
Too much recursion

### ISSUE THREAD

**Issue by FritzHoing** [terrestris/shogun-admin#715]
When inspecting a layer or an application i run into a `too much recursion` error. This error appeared with the springdoc-openapi update in this [MR](https://github.com/terrestris/shogun/pull/892/files).
When i customize my pom.xml and use the older springdoc-openapi version (2.5.0) everything works as expected.

**Comment by dnlkoch** [comment]
This should already be fixed in https://github.com/terrestris/shogun/pull/895.
